baseURL = 'https://leihao.github.io/'
languageCode = 'zh-cn'
title = '点灯大师'
theme = 'PaperMod'

[params]
ShowToc = true
ShowShareButtons = false
ShowReadingTime = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
comments = true

[params.meta]
favicon = false

[params.homeInfoParams]
Title = "宁静致远"
Content = "山高自有客行路，水深自有渡船人"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/zleihao"

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = false

[markup.highlight]
tabWidth = 4
noClasses = false
codeFences = true
guessSyntax = true
lineNos = true
style = "catppuccin-macchiato"
